services:
  express-app:
    image: ../express-app
    ports:
      - "8080:8080"
    container_name: my-express-app

  watchtower:
    image: containrrr/watchtower
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 my-express-app